<?php

$osname = $_POST['get_info'];
$myfile = fopen("info.json", "w");

fwrite($myfile, $osname);
fclose($myfile);

$getUserAgent =$_POST['getUserAgent']; 
$getUserAgentLowerCase =$_POST['getUserAgentLowerCase']; 
$getBrowser =$_POST['getBrowser']; 
$getBrowserVersion =$_POST['getBrowserVersion']; 
$getBrowserMajorVersion =$_POST['getBrowserMajorVersion']; 
$isIE =$_POST['isIE']; 
$isChrome =$_POST['isChrome']; 
$isFirefox =$_POST['isFirefox']; 
$isSafari =$_POST['isSafari']; 
$isOpera =$_POST['isOpera']; 
$getEngine =$_POST['getEngine']; 
$getEngineVersion =$_POST['getEngineVersion']; 
$getOS =$_POST['getOS']; 
$getOSVersion =$_POST['getOSVersion']; 
$isWindows =$_POST['isWindows']; 
$isMac =$_POST['isMac']; 
$isLinux =$_POST['isLinux']; 
$isUbuntu =$_POST['isUbuntu']; 
$isSolaris =$_POST['isSolaris']; 
$getDevice =$_POST['getDevice']; 
$getDeviceType =$_POST['getDeviceType']; 
$getDeviceVendor =$_POST['getDeviceVendor']; 
$getCPU =$_POST['getCPU']; 
$isMobile =$_POST['isMobile']; 
$isMobileMajor =$_POST['isMobileMajor']; 
$isMobileAndroid =$_POST['isMobileAndroid']; 
$isMobileOpera =$_POST['isMobileOpera']; 
$isMobileWindows =$_POST['isMobileWindows']; 
$isMobileBlackBerry =$_POST['isMobileBlackBerry']; 
$isMobileIOS =$_POST['isMobileIOS']; 
$isIphone =$_POST['isIphone']; 
$isIpad =$_POST['isIpad']; 
$getScreenPrint =$_POST['getScreenPrint']; 
$getColorDepth =$_POST['getColorDepth']; 
$getCurrentResolution =$_POST['getCurrentResolution']; 
$getAvailableResolution =$_POST['getAvailableResolution']; 
$getDeviceXDPI =$_POST['getDeviceXDPI']; 
$getDeviceYDPI =$_POST['getDeviceYDPI']; 
$getPlugins =$_POST['getPlugins']; 
$isJava =$_POST['isJava']; 
$getJavaVersion =$_POST['getJavaVersion']; 
$isFlash =$_POST['isFlash']; 
$getFlashVersion =$_POST['getFlashVersion']; 
$isSilverlight =$_POST['isSilverlight']; 
$getSilverlightVersion =$_POST['getSilverlightVersion']; 
$getMimeTypes =$_POST['getMimeTypes']; 
$isMimeTypes =$_POST['isMimeTypes']; 
$isFont =$_POST['isFont']; 
$getFonts =$_POST['getFonts']; 
$isLocalStorage =$_POST['isLocalStorage']; 
$isSessionStorage =$_POST['isSessionStorage']; 
$isCookie =$_POST['isCookie']; 
$getTimeZone =$_POST['getTimeZone']; 
$getLanguage =$_POST['getLanguage']; 
$getSystemLanguage =$_POST['getSystemLanguage']; 
$isCanvas =$_POST['isCanvas']; 
$getCanvasPrint =$_POST['getCanvasPrint']; 

$myfile = fopen("getUserAgent.json", "w");
$myfile = fopen("getUserAgentLowerCase.json", "w");
fwrite($myfile, $getUserAgent);
fclose($myfile);
$myfile = fopen("getBrowser.json", "w");
fwrite($myfile, $getUserAgentLowerCase);
fclose($myfile);
$myfile = fopen("getBrowserVersion.json", "w");
fwrite($myfile, $getBrowser);
fclose($myfile);
$myfile = fopen("getBrowserMajorVersion.json", "w");
fwrite($myfile, $getBrowserVersion);
fclose($myfile);
$myfile = fopen("isIE.json", "w");
fwrite($myfile, $getBrowserMajorVersion);
fclose($myfile);
$myfile = fopen("isChrome.json", "w");
fwrite($myfile, $isIE);
fclose($myfile);
$myfile = fopen("isFirefox.json", "w");
fwrite($myfile, $isChrome);
fclose($myfile);
$myfile = fopen("isSafari.json", "w");
fwrite($myfile, $isFirefox);
fclose($myfile);
$myfile = fopen("isOpera.json", "w");
fwrite($myfile, $isSafari);
fclose($myfile);
$myfile = fopen("getEngine.json", "w");
fwrite($myfile, $isOpera);
fclose($myfile);
$myfile = fopen("getEngineVersion.json", "w");
fwrite($myfile, $getEngine);
fclose($myfile);
$myfile = fopen("getOS.json", "w");
fwrite($myfile, $getEngineVersion);
fclose($myfile);
$myfile = fopen("getOSVersion.json", "w");
fwrite($myfile, $getOS);
fclose($myfile);
$myfile = fopen("isWindows.json", "w");
fwrite($myfile, $getOSVersion);
fclose($myfile);
$myfile = fopen("isMac.json", "w");
fwrite($myfile, $isWindows);
fclose($myfile);
$myfile = fopen("isLinux.json", "w");
fwrite($myfile, $isMac);
fclose($myfile);
$myfile = fopen("isUbuntu.json", "w");
fwrite($myfile, $isLinux);
fclose($myfile);
$myfile = fopen("isSolaris.json", "w");
fwrite($myfile, $isUbuntu);
fclose($myfile);
$myfile = fopen("getDevice.json", "w");
fwrite($myfile, $isSolaris);
fclose($myfile);
$myfile = fopen("getDeviceType.json", "w");
fwrite($myfile, $getDevice);
fclose($myfile);
$myfile = fopen("getDeviceVendor.json", "w");
fwrite($myfile, $getDeviceType);
fclose($myfile);
$myfile = fopen("getCPU.json", "w");
fwrite($myfile, $getDeviceVendor);
fclose($myfile);
$myfile = fopen("isMobile.json", "w");
fwrite($myfile, $getCPU);
fclose($myfile);
$myfile = fopen("isMobileMajor.json", "w");
fwrite($myfile, $isMobile);
fclose($myfile);
$myfile = fopen("isMobileAndroid.json", "w");
fwrite($myfile, $isMobileMajor);
fclose($myfile);
$myfile = fopen("isMobileOpera.json", "w");
fwrite($myfile, $isMobileAndroid);
fclose($myfile);
$myfile = fopen("isMobileWindows.json", "w");
fwrite($myfile, $isMobileOpera);
fclose($myfile);
$myfile = fopen("isMobileBlackBerry.json", "w");
fwrite($myfile, $isMobileWindows);
fclose($myfile);
$myfile = fopen("isMobileIOS.json", "w");
fwrite($myfile, $isMobileBlackBerry);
fclose($myfile);
$myfile = fopen("isIphone.json", "w");
fwrite($myfile, $isMobileIOS);
fclose($myfile);
$myfile = fopen("isIpad.json", "w");
fwrite($myfile, $isIphone);
fclose($myfile);
$myfile = fopen("isIpod.json", "w");
fwrite($myfile, $isIpad);
fclose($myfile);
$myfile = fopen("getScreenPrint.json", "w");
fwrite($myfile, $isIpod);
fclose($myfile);
$myfile = fopen("getColorDepth.json", "w");
fwrite($myfile, $getScreenPrint);
fclose($myfile);
$myfile = fopen("getCurrentResolution.json", "w");
fwrite($myfile, $getColorDepth);
fclose($myfile);
$myfile = fopen("getAvailableResolution.json", "w");
fwrite($myfile, $getCurrentResolution);
fclose($myfile);
$myfile = fopen("getDeviceXDPI.json", "w");
fwrite($myfile, $getAvailableResolution);
fclose($myfile);
$myfile = fopen("getDeviceYDPI.json", "w");
fwrite($myfile, $getDeviceXDPI);
fclose($myfile);
$myfile = fopen("getPlugins.json", "w");
fwrite($myfile, $getDeviceYDPI);
fclose($myfile);
$myfile = fopen("isJava.json", "w");
fwrite($myfile, $getPlugins);
fclose($myfile);
$myfile = fopen("getJavaVersion.json", "w");
fwrite($myfile, $isJava);
fclose($myfile);
$myfile = fopen("isFlash.json", "w");
fwrite($myfile, $getJavaVersion);
fclose($myfile);
$myfile = fopen("getFlashVersion.json", "w");
fwrite($myfile, $isFlash);
fclose($myfile);
$myfile = fopen("isSilverlight.json", "w");
fwrite($myfile, $getFlashVersion);
fclose($myfile);
$myfile = fopen("getSilverlightVersion.json", "w");
fwrite($myfile, $isSilverlight);
fclose($myfile);
$myfile = fopen("getMimeTypes.json", "w");
fwrite($myfile, $getSilverlightVersion);
fclose($myfile);
$myfile = fopen("isMimeTypes.json", "w");
fwrite($myfile, $getMimeTypes);
fclose($myfile);
$myfile = fopen("isFont.json", "w");
fwrite($myfile, $isMimeTypes);
fclose($myfile);
$myfile = fopen("getFonts.json", "w");
fwrite($myfile, $isFont);
fclose($myfile);
$myfile = fopen("isLocalStorage.json", "w");
fwrite($myfile, $getFonts);
fclose($myfile);
$myfile = fopen("isSessionStorage.json", "w");
fwrite($myfile, $isLocalStorage);
fclose($myfile);
$myfile = fopen("isCookie.json", "w");
fwrite($myfile, $isSessionStorage);
fclose($myfile);
$myfile = fopen("getTimeZone.json", "w");
fwrite($myfile, $isCookie);
fclose($myfile);
$myfile = fopen("getLanguage.json", "w");
fwrite($myfile, $getTimeZone);
fclose($myfile);
$myfile = fopen("getSystemLanguage.json", "w");
fwrite($myfile, $getLanguage);
fclose($myfile);
$myfile = fopen("isCanvas.json", "w");
fwrite($myfile, $getSystemLanguage);
fclose($myfile);
$myfile = fopen("getCanvasPrint.json", "w");
fwrite($myfile, $isCanvas);
fclose($myfile);
fwrite($myfile, $getCanvasPrint);
fclose($myfile);
